apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-rest-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: books-rest-api
  template:
    metadata:
      labels:
        app: books-rest-api
    spec:
      containers:
        - name: books-rest-api
          image: localhost:5000/books-rest-api:1.0  # OR {docker-id}/books-rest-api:1.0
          ports:
            - containerPort: 8080