-- Books table schema
CREATE TABLE books (
    book_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title    VARCHAR(50) NOT NULL,
    author    VARCHAR(50) NOT NULL,
    description    VARCHAR(256) NOT NULL,
    isbn VARCHAR(50) NOT NULL
);

-- Users table schema
CREATE TABLE users (
    user_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(50) NOT NULL,
    password    VARCHAR(256) NOT NULL,
    authority    VARCHAR(40) NOT NULL
);